package calculadora;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class Login extends javax.swing.JFrame {
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.OCULTAR.setVisible(false);
    }

    private void transparencia(){
        jButton1.setOpaque(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Usuario = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        OCULTAR = new javax.swing.JLabel();
        VER = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Usuario.setBackground(new java.awt.Color(36, 42, 56));
        txt_Usuario.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txt_Usuario.setForeground(new java.awt.Color(254, 254, 254));
        txt_Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 42, 56)));
        txt_Usuario.setOpaque(true);
        txt_Usuario.setSelectionColor(new java.awt.Color(36, 42, 56));
        txt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 490, 34));

        txt_password.setBackground(new java.awt.Color(36, 42, 56));
        txt_password.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(254, 254, 254));
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 42, 56)));
        txt_password.setOpaque(true);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 430, 34));

        OCULTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/oculto.png"))); // NOI18N
        OCULTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OCULTARMouseClicked(evt);
            }
        });
        getContentPane().add(OCULTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        VER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ver.png"))); // NOI18N
        VER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VERMouseClicked(evt);
            }
        });
        getContentPane().add(VER, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ingresar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 70));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de acceso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/rect2009_1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsuarioKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if (Character.isDigit(validar)){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane,"Ingresar solo letras","ERROR",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_txt_UsuarioKeyTyped

    private void VERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERMouseClicked
         VER.setVisible(false);
        OCULTAR.setVisible(true);
        txt_password.setEchoChar((char)0);
    }//GEN-LAST:event_VERMouseClicked

    private void OCULTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OCULTARMouseClicked
       VER.setVisible(true);
        OCULTAR.setVisible(false);
        txt_password.setEchoChar('●');
    }//GEN-LAST:event_OCULTARMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 String Usuario = "profeNoe";
        String Contraseña = "12345";
        String pass = new String (txt_password.getPassword());
        if(txt_Usuario.getText().equals(Usuario) && pass.equals(Contraseña)){
            Login s1 = new Login();
            s1.setVisible(true);
            dispose();

        }else{
            if(txt_Usuario.getText().equals(Usuario)){
                JOptionPane.showMessageDialog(this, " contraseña incorrecta " , " ERROR ", JOptionPane.ERROR_MESSAGE);
            }else{
                if(txt_password.getText().equals(Contraseña)){
                    JOptionPane.showMessageDialog(this, " usuario incorrecto " , " ERROR ", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, " usuario y contraseña incorrectos" , " ERROR ", JOptionPane.ERROR_MESSAGE);
                    {
                    }}}}
    }//GEN-LAST:event_jButton1MouseClicked

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_passwordKeyTyped
   public static boolean validarNumeros(String datos)   {
        return datos.matches("[0-9]");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OCULTAR;
    private javax.swing.JLabel VER;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

    }
